---
# tasks file for bc.maxscale
- name: install libcurl3
  apt:
    name: libcurl3
    state: present

- name: install maxscale
  apt:
    name: maxscale
    state: present

- name: backup from maxscale.cnf file
  shell: mv /etc/maxscale.cnf /etc/maxscale.cnf.bak

- name: create maxscale.cnf with an template
  template:
    src: /templates/maxscale/maxscale.cnf.j2
    dest: /etc/maxscale/maxscale.cnf
    mode: 0644
  notify: restart maxscale
