---
# tasks file for bc.maxscale
- name: install libcurl3
  apt:
    name: libcurl3
    state: present

- name: install maxscale
  apt:
    name: maxscale
    state: present

- name: create maxscale.cnf with an template
  template:
    src: templates/maxscale.cnf.j2
    dest: /etc/maxscale.cnf
  notify: restart maxscale
